name: side_swap_ffi

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  ffigen: ^3.0.0
  flutter_lints: ^1.0.4

ffigen:
  name: NativeLibrary
  output: '../lib/side_swap_client_ffi.dart'
  description: 'SideSwap FFI'
  headers:
    entry-points:
      - 'gen/side_swap_client_ffi.h'
  functions:
    include:
      - 'sideswap_.*'
  llvm-path:
    - 'usr/lib/llvm-11'