name: sideswap
description: Sideswap Client.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.4+55

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  # secure recovery page
  secure_application: ^3.8.0
  animations: ^2.0.3
  another_flushbar: ^1.10.27

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  delayed_display: ^2.0.0
  dotted_line: ^3.1.0
  easy_localization: ^3.0.1
  enum_to_string: ^2.0.1
  # testing only - remove if not used
  faker: ^2.0.0
  firebase_core: ^1.17.1
  #firebase notifications
  firebase_messaging: ^11.4.1
  fixnum: ^1.0.1
  # contacts
  flutter_contacts: ^1.1.4
  # icon generator
  flutter_launcher_icons_maker: ^0.10.2
  #notifications
  flutter_local_notifications: ^9.7.0
  flutter_plugin_android_lifecycle: ^2.0.6
  # screen scaling
  flutter_screenutil: ^5.5.3+2
  # license loading indicator
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.0
  # switch
  flutter_switch: ^0.3.2
  # mnemonic words suggestions
  flutter_typeahead: ^4.0.0
  # notification payload parsing
  freezed_annotation: ^2.0.3
  # because of 1.0.3 bug https://github.com/rrousselGit/river_pod/issues/815
  hooks_riverpod: ^2.0.0-dev.9
  flutter_hooks: ^0.18.4
  image: ^3.1.3 # update me
  # avatar
  image_picker: ^0.8.5+3
  json_annotation: ^4.5.0
  # logger
  logger: ^1.1.0
  # marqee text
  marquee: ^2.2.2
  # background
  path_drawing: ^1.0.0
  path_provider: ^2.0.10
  # permissions (contacts)
  permission_handler: ^9.2.0
  # pin
  pinput: ^1.2.2 # update me
  protobuf: ^2.0.1
  mobile_scanner: ^1.1.1
  qr_flutter: ^4.0.0
  # rxdart
  rxdart: ^0.27.3
  share_plus: ^4.0.4
  shared_preferences: ^2.0.15
  # sliding tx list
  sliding_up_panel: ^2.0.0+1
  # deep/app links
  uni_links: ^0.5.1
  url_launcher: ^6.1.2
  # sound notification
  flutter_ringtone_player: ^3.2.0
  vibration: ^1.7.4-nullsafety.0
  move_to_background: ^1.0.2
  decimal: ^1.5.0 # update me
  xrange: ^2.0.0
  # list comparision
  collection: ^1.16.0
  csv: ^5.0.1
  tuple: ^2.0.0
  vector_math: ^2.1.2
  http: ^0.13.4

  #desktop
  window_manager: ^0.2.3
  args: ^2.3.1
  matrix4_transform: ^2.0.1
  candlesticks:
    path: thirdparty/candlesticks
  file_selector: ^0.8.4+2
  file_selector_linux: ^0.0.2+1
  file_selector_macos: ^0.8.2+1
  file_selector_windows: ^0.8.2+1
  ffi: ^2.0.0


dependency_overrides:
  rxdart: ^0.27.3
  ffi: ^2.0.0

  flutter_local_notifications_platform_interface:
    git:
      url: https://github.com/kennethnym/flutter_local_notifications.git
      path: flutter_local_notifications_platform_interface
      ref: 0baa7db0b641e18158e7690c874e1b2458649543

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^4.1.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - LICENSE
    - assets/licenses/
    - images/icon_btc.png
    - images/check_mark.svg
    - images/swap.svg
    - assets/wordlist.txt
    - assets/translations/
    - assets/translations/icons/
    - assets/btc_logo.svg
    - assets/usdt_logo.svg
    - assets/lbtc_logo.svg
    - assets/accounts.svg
    - assets/accounts_active.svg
    - assets/home.svg
    - assets/home_active.svg
    - assets/requests.svg
    - assets/requests_active.svg
    - assets/swap.svg
    - assets/swap_active.svg
    - assets/logo.svg
    - assets/settings.svg
    - assets/top_right_arrow.svg
    - assets/bottom_left_arrow.svg
    - assets/qr_code_scan.svg
    - assets/qr_icon.svg
    - assets/filter.svg
    - assets/back_arrow.svg
    - assets/search.svg
    - assets/mini_button.svg
    - assets/tx_peg_in.svg
    - assets/tx_swap.svg
    - assets/share.svg
    - assets/share2.svg
    - assets/share3.svg
    - assets/copy.svg
    - assets/close.svg
    - assets/swap_arrows.svg
    - assets/info.svg
    - assets/error.svg
    - assets/success.svg
    - assets/recovery.svg
    - assets/shield.svg
    - assets/about.svg
    - assets/delete.svg
    - assets/shield_big.svg
    - assets/locker.svg
    - assets/locker2.svg
    - assets/locker3.svg
    - assets/exclamationMark.svg
    - assets/web_icon.svg
    - assets/github_icon.svg
    - assets/twitter_icon.svg
    - assets/telegram_icon.svg
    - assets/avatar.svg
    - assets/associate_phone.svg
    - assets/phone.svg
    - assets/edit.svg
    - assets/user_details.svg
    - assets/male1.svg
    - assets/male2.svg
    - assets/female1.svg
    - assets/device_frame.svg
    - assets/blinded.svg
    - assets/unblinded.svg
    - assets/link.svg
    - assets/link2.svg
    - assets/network.svg
    - assets/restart.svg
    - assets/faq.svg
    - assets/lock.svg
    - assets/volume_filter.svg
    - assets/export.svg
    - assets/asset_swap_arrows.svg
    - assets/tx_icons/recv.svg
    - assets/tx_icons/sent.svg
    - assets/tx_icons/swap.svg
    - assets/tx_icons/internal.svg
    - assets/tx_icons/unknown.svg
    - assets/arrow_up.svg
    - assets/arrow_down.svg
    - assets/copy2.svg
    - assets/transactions.svg
    - assets/transactions_active.svg
    - assets/toolbar/recv.svg
    - assets/toolbar/send.svg
    - assets/toolbar/settings.svg
    - assets/toolbar/open_url.svg
    - assets/close2.svg
    - assets/close3.svg
    - assets/paste.svg
    - assets/tx_icons/pegin.svg
    - assets/tx_icons/pegout.svg
    - assets/chart.svg
    - assets/clock.svg
    - assets/edit2.svg
    - assets/delete2.svg
    - assets/copy3.svg
    - assets/success2.svg
    - assets/icon/icon.ico
    - assets/icon/icon_linux.png
    - assets/arrow_back3.svg
    - assets/arrow_down2.svg
    - assets/arrow_up2.svg
    - assets/language.svg
    - assets/peg-in-out.svg
    - assets/peg-in-out_active.svg
    - assets/jade.svg
    - assets/jade_front_idle.svg
    - assets/jade_front_unlock.svg
    - assets/question_mark.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
