[package]
name = "sideswap_dealer"
version = "0.1.2"
edition = "2021"

[dependencies]
sideswap_api = { path = "../sideswap_api" }
sideswap_common = { path = "../sideswap_common" }

anyhow.workspace = true
base64.workspace = true
crossbeam-channel.workspace = true
elements = { workspace = true, features = ["serde"] }
hex.workspace = true
log.workspace = true
rand.workspace = true
reqwest = { workspace = true, default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
