include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "lib/side_swap_client_ffi.dart"
    - "lib/protobuf/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/common/utils/country_codes.dart"
    - "ffi/*"
    - "lib/common_platform_mobile.dart"
    - "lib/models/notifications_service.dart"
    - "lib/common_platform_desktop.dart"
  errors:
    implicit_dynamic_parameter: warning
    invalid_annotation_target: ignore