[package]
name = "sideswap_jade"
version = "0.1.2"
edition = "2018"

[dependencies]
log = "*"
hex = "*"
ciborium = "*"
ciborium-io = "*"
anyhow = "*"
serde = "*"
ureq = "2.0"
serde_json = "*"
serde_bytes = "*"
base64 = "*"
crossbeam-channel = "0.5.1"

[target.'cfg(any(target_os = "windows", target_os = "linux", target_os = "macos"))'.dependencies]
serialport = { git = "https://github.com/serialport/serialport-rs", rev = "08c1b61f6c748776a8a2786b88ccf7c25623719a" }
