[package]
name = "sideswap_jade"
version = "0.1.2"
edition = "2018"

[dependencies]
log = "*"
hex = "*"
ciborium = "*"
ciborium-io = "*"
anyhow = "*"
serde = "*"
ureq = "2.0"
serde_json = "*"
serde_bytes = "*"
base64 = "*"
crossbeam-channel = "0.5.1"

[target.'cfg(any(target_os = "windows", target_os = "linux", target_os = "macos"))'.dependencies]
serialport = "4.1.0"
