targets:
  $default:
    sources:
        - lib/models/**.dart
        - pubspec.*
        - $package$
        - lib/$lib$
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: true
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
      freezed:
        generate_for:
          - "lib/models/notification_model.dart"
          - "lib/models/swap_models.dart"
          - "lib/models/pin_models.dart"
          - "lib/models/qrcode_models.dart"
          - "lib/models/amount_to_string_model.dart"
          - "lib/models/stokr_model.dart"
          - "lib/models/pegx_model.dart"
