name: sideswap
description: Sideswap Client.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.0+59

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  # secure recovery page
  secure_application: ^3.8.0
  animations: ^2.0.7
  another_flushbar: ^1.12.29

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  delayed_display: ^2.0.0
  dotted_line: ^3.1.0
  easy_localization: ^3.0.1
  enum_to_string: ^2.0.1
  # testing only - remove if not used
  faker: ^2.1.0
  #firebase notifications
  fixnum: ^1.1.0
  # contacts
  flutter_contacts: ^1.1.5+1
  #notifications

  flutter_local_notifications: # update me
    git:
      url: https://github.com/kennethnym/flutter_local_notifications.git
      path: flutter_local_notifications
      ref: 0baa7db0b641e18158e7690c874e1b2458649543

  flutter_plugin_android_lifecycle: ^2.0.7
  # license loading indicator
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.0+1
  # switch
  flutter_switch: ^0.3.2
  # mnemonic words suggestions
  flutter_typeahead: ^4.3.3
  # notification payload parsing
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.0
  flutter_hooks: ^0.18.6
  image: ^4.0.15
  # avatar
  image_picker: ^0.8.6+1
  json_annotation: ^4.8.0
  # logger
  logger: ^1.1.0
  # marqee text
  marquee: ^2.2.3
  # background
  path_drawing: ^1.0.1
  path_provider: ^2.0.12
  # pin
  pinput: ^1.2.2 # update me
  protobuf: ^2.1.0
  qr_flutter: ^4.0.0
  # rxdart
  rxdart: ^0.27.7
  share_plus: ^6.3.0
  shared_preferences: ^2.0.17
  # sliding tx list
  sliding_up_panel: ^2.0.0+1
  # deep/app links
  uni_links: ^0.5.1 # replace by app_links
  url_launcher: ^6.1.9
  # sound notification
  flutter_ringtone_player: ^3.2.0
  vibration: ^1.7.6
  move_to_background: ^1.0.2
  decimal: ^1.5.0 # update me
  xrange: ^2.0.0
  # list comparision
  collection: ^1.17.0
  csv: ^5.0.1
  tuple: ^2.0.1
  vector_math: ^2.1.4
  http: ^0.13.5
  cached_memory_image: ^1.3.1
  equatable: ^2.0.5

  #desktop
  window_manager: ^0.3.0 # prev: 0.2.3, 0.2.5 crashes on linux!
  args: ^2.3.2
  matrix4_transform: ^2.0.1
  candlesticks:
    path: thirdparty/candlesticks
  file_selector: ^0.9.2+2 # prev: ^0.8.4+2
  file_selector_linux: ^0.9.1 # prev: ^0.0.2+1
  file_selector_macos: ^0.9.0+4  #prev: ^0.8.2+1
  file_selector_windows: ^0.9.1+4 #prev ^0.8.2+1
  ffi: ^2.0.1
  web_socket_channel: ^2.3.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: a738913c8ce2c9f47515382d40827e794a334274

dependency_overrides:
  rxdart: ^0.27.7
    
  flutter_local_notifications_platform_interface:
    git:
      url: https://github.com/kennethnym/flutter_local_notifications.git
      path: flutter_local_notifications_platform_interface
      ref: 0baa7db0b641e18158e7690c874e1b2458649543

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^5.6.0
  build_runner: ^2.3.3 # after update remove file: ^6.1.4 and check is it working fine!
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  # icon generator
  #flutter_launcher_icons_maker: ^0.10.2
  icons_launcher: ^2.0.7
  file: ^6.1.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - LICENSE
    - assets/licenses/
    - images/icon_btc.png
    - images/check_mark.svg
    - images/swap.svg
    - assets/wordlist.txt
    - assets/translations/
    - assets/translations/icons/
    - assets/btc_logo.svg
    - assets/usdt_logo.svg
    - assets/lbtc_logo.svg
    - assets/accounts.svg
    - assets/accounts_active.svg
    - assets/home.svg
    - assets/home_active.svg
    - assets/requests.svg
    - assets/requests_active.svg
    - assets/swap.svg
    - assets/swap_active.svg
    - assets/logo.svg
    - assets/settings.svg
    - assets/top_right_arrow.svg
    - assets/bottom_left_arrow.svg
    - assets/qr_code_scan.svg
    - assets/qr_icon.svg
    - assets/filter.svg
    - assets/back_arrow.svg
    - assets/search.svg
    - assets/mini_button.svg
    - assets/tx_peg_in.svg
    - assets/tx_swap.svg
    - assets/share.svg
    - assets/share2.svg
    - assets/share3.svg
    - assets/copy.svg
    - assets/close.svg
    - assets/swap_arrows.svg
    - assets/info.svg
    - assets/error.svg
    - assets/success.svg
    - assets/recovery.svg
    - assets/shield.svg
    - assets/about.svg
    - assets/delete.svg
    - assets/shield_big.svg
    - assets/locker.svg
    - assets/locker2.svg
    - assets/locker3.svg
    - assets/exclamationMark.svg
    - assets/web_icon.svg
    - assets/web_icon_transparent.svg
    - assets/github_icon.svg
    - assets/twitter_icon.svg
    - assets/telegram_icon.svg
    - assets/avatar.svg
    - assets/associate_phone.svg
    - assets/phone.svg
    - assets/edit.svg
    - assets/user_details.svg
    - assets/male1.svg
    - assets/male2.svg
    - assets/female1.svg
    - assets/device_frame.svg
    - assets/blinded.svg
    - assets/unblinded.svg
    - assets/link.svg
    - assets/link2.svg
    - assets/network.svg
    - assets/restart.svg
    - assets/faq.svg
    - assets/lock.svg
    - assets/volume_filter.svg
    - assets/export.svg
    - assets/asset_swap_arrows.svg
    - assets/tx_icons/recv.svg
    - assets/tx_icons/sent.svg
    - assets/tx_icons/swap.svg
    - assets/tx_icons/internal.svg
    - assets/tx_icons/unknown.svg
    - assets/arrow_up.svg
    - assets/arrow_down.svg
    - assets/copy2.svg
    - assets/transactions.svg
    - assets/transactions_active.svg
    - assets/toolbar/recv.svg
    - assets/toolbar/send.svg
    - assets/toolbar/settings.svg
    - assets/toolbar/open_url.svg
    - assets/close2.svg
    - assets/close3.svg
    - assets/paste.svg
    - assets/tx_icons/pegin.svg
    - assets/tx_icons/pegout.svg
    - assets/chart.svg
    - assets/clock.svg
    - assets/edit2.svg
    - assets/delete2.svg
    - assets/copy3.svg
    - assets/success2.svg
    - assets/icon/icon.ico
    - assets/icon/icon_linux.png
    - assets/arrow_back3.svg
    - assets/arrow_down2.svg
    - assets/arrow_up2.svg
    - assets/language.svg
    - assets/peg-in-out.svg
    - assets/peg-in-out_active.svg
    - assets/jade.svg
    - assets/jade_front_idle.svg
    - assets/jade_front_unlock.svg
    - assets/question_mark.svg
    - assets/stokr_logo.svg
    - assets/pegx_logo.svg
    - assets/bmn.svg
    - assets/amp_image.svg
    - assets/autheid_logo.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
