[package]
name = "sideswap_common"
version = "0.1.2"
edition = "2018"

[dependencies]
sideswap_api = { version = "*", path = "../sideswap_api" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
anyhow = "*"
log = "*"
async-tungstenite = { version = "0.16.1", features = ["tokio-runtime", "tokio-rustls-webpki-roots"] }
futures = "*"
futures-util = "*"
tokio = { version = "1.15.0", default-features = false, features = ["macros", "net", "rt", "sync", "time"] }
tungstenite = { version = "*", default-features = false, features = [] }
derive_more = "*"
bitcoin = { version = "0.26" }
elements = "*"
elements_pset = { package = "elements", git = "https://github.com/sanket1729/rust-elements", rev = "dc350a0b8664cdd5b051443810a6a1f99a6173da" }
rand = "0.6.5"
crossbeam-channel = "0.5.1"

[dev-dependencies]
hex = "*"
