[package]
name = "sideswap_common"
version = "0.1.2"
edition = "2021"

[dependencies]
sideswap_api = { path = "../sideswap_api" }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
anyhow.workspace = true
log.workspace = true
tokio-tungstenite = { workspace = true, features = [ "stream", "rustls-tls-webpki-roots" ] }
futures.workspace = true
futures-util.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt", "sync", "time"] }
tungstenite = { workspace = true, default-features = false, features = [] }
derive_more.workspace = true
bitcoin = { workspace = true }
elements = { workspace = true, features = ["serde"] }
rand.workspace = true
crossbeam-channel.workspace = true
tokio-socks.workspace = true

[dev-dependencies]
hex.workspace = true
