[workspace]

members = [
    "sideswap_api",
    "sideswap_common",
    "sideswap_headless",
    "sideswap_headless_trader",
    "sideswap_client",
    "sideswap_jade",
    "sideswap_dealer",
    "sideswap_dealer_ws",
    "sideswap_dealer_example",
    "sideswap_dealer_bitfinex",
    "gdk_rust/gdk_common",
    "gdk_rust/gdk_electrum",
    "gdk_rust/gdk_rust",
    "gdk_rust/gdk_registry",
]
