[package]
name = "sideswap_client"
version = "0.1.2"
edition = "2018"
build = "build.rs"

[lib]
name = "sideswap_client"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
sideswap_api = { version = "*", path = "../sideswap_api" }
sideswap_common = { version = "*", path = "../sideswap_common" }
sideswap_jade = { version = "*", path = "../sideswap_jade" }
elements = { git = "https://github.com/ElementsProject/rust-elements", rev = "53d5729f8cdc3623f9f110edba86aeaa9059af5b", features = ["serde-feature"] }
elements_pset = { package = "elements", git = "https://github.com/sanket1729/rust-elements", rev = "dc350a0b8664cdd5b051443810a6a1f99a6173da" }
bitcoin = { version = "0.27.1", features = [ "use-serde" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_bytes = "*"
log = "*"
anyhow = "*"
flexi_logger = "*"
derive_more = "*"
base64 = "*"
gdk-rust = { path = "../gdk_rust" }
gdk-electrum = { path = "../gdk_rust/gdk_electrum" }
gdk-common = { path = "../gdk_rust/gdk_common" }
libc = "*"
prost = "0.6.1"
bytes = "*"
allo-isolate = "*"
chrono = "*"
hex = "*"
rand = "0.6.5"
bip39 = "1.0.1"
ureq = "1.5"
time = {version= "0.3.5", features = ["local-offset", "formatting", "macros", "parsing"]}
crossbeam-channel = "0.5.1"
tokio = { version = "1.15.0", default-features = false, features = ["macros", "net", "rt", "sync", "time"] }
secp256k1 = "*"

[build-dependencies]
prost-build = "0.6.1"
vergen = { version = "5", default-features = false, features = ["build", "rustc", "git"] }
